ktor:
    application:
        modules:
            - com.example.ApplicationKt.koin
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
        sslPort: 8443

    security:
        ssl:
            keyStore: keystore.jks
            keyAlias: $KEY_ALIAS
            keyStorePassword: $KEY_STORE_PASSWORD
            privateKeyPassword: $PRIVATE_KEY_PASSWORD

    database:
        jdbcURL: $JDBC_URL
        driverClassName: $DRIVER_CLASS_NAME
        username: $DB_USERNAME
        password: $DB_PASSWORD

    auth:
        webClientId: $WEB_CLIENT_ID
