ktor:
    application:
        modules:
            - com.example.ApplicationKt.koin
            - com.example.ApplicationKt.module
    deployment:
        port: 8080

    database:
        jdbcURL: $JDBC_URL
        driverClassName: $DRIVER_CLASS_NAME
        username: $DB_USERNAME
        password: $DB_PASSWORD

    auth:
        webClientId: TODO
