ktor:
    application:
        modules:
            - com.example.ApplicationKt.koin
            - com.example.ApplicationKt.module
    deployment:
        port: 8080

    database:
        jdbcURL: "jdbc:mariadb://localhost:3306/tech_quiz"
        driverClassName: "org.mariadb.jdbc.Driver"
        username: $DB_USERNAME
        password: $DB_PASSWORD

    auth:
        webClientId: TODO
